### ISSUE TITLE
Artisan command to create block template uses folder …/components while Block.php searches in …/blocks

### ISSUE THREAD

**Issue by papoms** [RicLeP/laravel-storyblok#2]
Hey there, thanks for the package!

While following the [documentation about Blocks](https://ls.sirric.co.uk/docs/2.4/blocks) i ran into an issue with my blocks not being rendered properly.

`php artisan ls:block MyComponent -b`
Creates a template in ressources/views/storyblok/**components**/my-component.blade.php.
This will not be found by the Block Class automatically. It expects the templates to reside in ressources/views/storyblok/**blocks**/ see https://github.com/RicLeP/laravel-storyblok/blob/aa7412b2ee8c94e8d70508824eb0d226da845ac3/src/Block.php#L142

Once i renamed the folder the template gets used.

**Comment by RicLeP** [comment]
Thanks, this will be fixed in the next release. I was torn between calling them blocks or components. I think a ‘block’ is an instance of a ‘component’ in Storyblok. I’m using ‘blocks’ though as it keeps the language more consistent in the package.

Out of interest, was this using the $block->render() method? It’s something I added bu don’t tend to use myself. Usually I loop over the data and use @include to select the Blade file passing in the content then I can specify the path.

```
@foreach($story->body as $item)
		@include('storyblok.components.body-blocks.' . $item->component(), ['content' => $item])
@endforeach
```

**Comment by papoms** [comment]
> Out of interest, was this using the `$block->render()` method? It’s something I added bu don’t tend to use myself. 
Exactly in my main page blade template i use:
```blade
@if ($story->body)
  @foreach ($story->body as $block)
    {{ $block->render() }}
  @endforeach
@endif
```
